name: 'Chromatic'

on:
  workflow_dispatch:
  issue_comment:
    types: [created, edited]
  merge_group:
    types: [checks_requested]
    branches: [main]

jobs:
  Chromatic:
    permissions: write-all
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' || (github.event.issue.pull_request  && contains(github.event.comment.body, '/chromatic')) || github.event_name == 'merge_group'
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Fetch all branches
        run: git fetch --all

      - name: Setup Node.js
        uses: actions/setup-node@v4

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Publish to Chromatic
        uses: chromaui/action@latest
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          skip: ${{ github.event_name == 'merge_group' }}

      - name: Update PR status
        env:
            GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
            OWNER: MidnightStudioGames
            REPO: Test-Chromatic
            SHA: ${{ github.sha }}
        run: |
            curl -L \
              -X POST \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer $GITHUB_TOKEN" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              https://api.github.com/repos/$OWNER/$REPO/statuses/$SHA \
              -d '{
                "state": "success",
                "target_url": "https://github.com/$OWNER/$REPO/actions/runs/${{ github.run_id }}",
                "description": "Chromatic deployment succeeded",
                "context": "Chromatic"
              }'
  
      - name: Mark as success
        run: exit 0
  
