name: 'Chromatic'

on:
  workflow_dispatch:
  issue_comment:
    types: [created, edited]
  merge_group:
    types: [checks_requested]
    branches: [main]

jobs:
  Chromatic:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' || (github.event.issue.pull_request  && contains(github.event.comment.body, '/chromatic')) || github.event_name == 'merge_group'
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Fetch all branches
        run: git fetch --all

      - name: Check for changes in components folder
        id: check_changes
        run: |
          CHANGED_FILES=$(git diff --name-only origin/main HEAD)
          echo "Changed files: $CHANGED_FILES"
          if echo "$CHANGED_FILES" | grep -q '^src/components/.*\.tsx$'; then
            echo "changes=true" >> $GITHUB_OUTPUT
          else
            echo "changes=false" >> $GITHUB_OUTPUT
          fi

      - name: Setup Node.js
        uses: actions/setup-node@v4

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Publish to Chromatic
        uses: chromaui/action@latest
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          skip: ${{ github.event_name == 'merge_group' }}
